language: csharp
sudo: required
mono: none
dotnet: 3.1
os: windows
matrix:
  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  include:
    # Windows
    - env: TARGET=x86_64-pc-windows-gnu

solution: ./calculadora-safra.sln

install:
- dotnet restore ./calculadora-safra.sln
script:
 - dotnet build ./calculadora-safra.sln

before_deploy:
- dotnet pack -c Release

deploy:
  skip_cleanup: true
  on:
    branch: CB-05
