language: csharp
mono: none
script:
- dotnet restore
os: windows

#before_install:
#  - curl "${GRAVIS}.disable-windows-defender.sh" --output .disable-windows-defender.sh
#  - source .disable-windows-defender.sh

#solution: calculadora-safra.sln

script:
#- dotnet restore ./calculadora-safra.sln
- dotnet build calculadora-safra.sln

before_deploy:
- dotnet pack -c Release

deploy:
 skip_cleanup: true
 on:
   branch: CB-05
