language: csharp
mono: none
os: windows
script:
- choco install dotnetcore-sdk
- dotnet --version
- dotnet restore
- dotnet build

solution: calculadora-safra.sln

#script:
#- dotnet restore
#- dotnet build

before_deploy:
- dotnet pack -c Release
- dotnet run

deploy:
 skip_cleanup: true
 on:
   branch: CB-05
